sudo: required
services:
  - docker
script:
  - echo "Hello Students!"
before_install:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh $EC2_INSTANCE 'bash ./deploy.sh'
  on:
    branch: master
