sudo: required
services:
  - docker
script:
  - echo "Hello Students!"
before_install:
  - mkdir -p ~/.ssh
  - echo -e "$PROD_SSH_KEY" > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "HOST *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config


deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
